/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./armchiarCobra.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArmchairCobra(props) {
  const { nodes, materials } = useGLTF('ArmchairCobra/armchiarCobra.gltf')
  return (
    <group {...props} dispose={null} rotation={[0,  Math.PI, 0]}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Body_Cut.geometry} material={materials.Paint_Main} position={[0, 0.331, -0.012]} />
        <mesh geometry={nodes.Body_pasy001.geometry} material={materials.Stripes} position={[0, 0.331, -0.012]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Chrome_dark} position={[0.552, 0.338, 0.539]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder008.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder009.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder010.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder013.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder014.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder015.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder016.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Floor001.geometry} material={materials.Flat_Black} position={[0, 0.005, 0.012]} />
        <mesh geometry={nodes.Migacz_obudowa.geometry} material={materials.Chrome} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_obudowa001.geometry} material={materials.Chrome} position={[-0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_uszczelka.geometry} material={materials.Rubber} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_uszczelka001.geometry} material={materials.Rubber} position={[-0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Siedzisko.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko003.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko004.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko_bok.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Szew391.geometry} material={materials.Stitch} position={[0.175, 0.62, -0.253]} />
        <mesh geometry={nodes.Taillamp002.geometry} material={materials.Taillamp} />
        <mesh geometry={nodes.Taillamp003.geometry} material={materials.Taillamp} />
        <mesh geometry={nodes.Taillight_Housing.geometry} material={materials.Chrome} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Wlew_czapka.geometry} material={materials.Chrome_Fuel_Cap} position={[0.663, 0.625, 0.113]} />
        <mesh geometry={nodes.Wlew_dol.geometry} material={materials.Chrome_Fuel_Cap} position={[0.599, 0.625, 0.113]} />
        <mesh geometry={nodes.Wlew_jezyk.geometry} material={materials.Chrome_Fuel_Cap} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_sprezynka.geometry} material={materials.Metal} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_zawias_A.geometry} material={materials.Metal_Rough} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_zawias_B.geometry} material={materials.Chrome_dark} position={[0.663, 0.625, 0.113]} />
        <mesh geometry={nodes.Zderzak_lezka.geometry} material={materials.Chrome} position={[0.425, 0.283, 0.544]} />
        <mesh geometry={nodes.Zderzak_lezka001.geometry} material={materials.Chrome} position={[-0.425, 0.283, 0.544]} />
        <mesh geometry={nodes.Zderzak_lezka_lacznik.geometry} material={materials.Metal} position={[0.425, 0.222, 0.579]} />
        <mesh geometry={nodes.Zderzak_lezka_lacznik001.geometry} material={materials.Metal} position={[-0.425, 0.222, 0.579]} />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Body_Cut001.geometry} material={materials.Paint_Main} position={[0, 0.331, -0.012]} />
        <mesh geometry={nodes.Body_pasy004.geometry} material={materials.Stripes} position={[0, 0.331, -0.012]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.Chrome_dark} position={[0.552, 0.338, 0.539]} />
        <mesh geometry={nodes.Cylinder001003.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder002003.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder003003.geometry} material={materials.Chrome_dark} position={[0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder008001.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder009001.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder010001.geometry} material={materials.Chrome_dark} position={[-0.383, 0, 0.327]} />
        <mesh geometry={nodes.Cylinder011003.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder012003.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder013001.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder014001.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder015001.geometry} material={materials.Chrome_dark} position={[-0.453, 0, -0.384]} />
        <mesh geometry={nodes.Cylinder016003.geometry} material={materials.Chrome_dark} position={[0.453, 0, -0.384]} />
        <mesh geometry={nodes.Floor002.geometry} material={materials.Flat_Black} position={[0, 0.005, 0.012]} />
        <mesh geometry={nodes.Migacz_obudowa003.geometry} material={materials.Chrome} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_obudowa001001.geometry} material={materials.Chrome} position={[-0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_uszczelka003.geometry} material={materials.Rubber} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Migacz_uszczelka001001.geometry} material={materials.Rubber} position={[-0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Siedzisko009.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko010.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko011.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Siedzisko_bok005.geometry} material={materials.Leather_Armchair} position={[0, 0.239, 0.105]} />
        <mesh geometry={nodes.Szew391001.geometry} material={materials.Stitch} position={[0.175, 0.62, -0.253]} />
        <mesh geometry={nodes.Taillamp004.geometry} material={materials.Taillamp} />
        <mesh geometry={nodes.Taillamp005.geometry} material={materials.Taillamp} />
        <mesh geometry={nodes.Taillight_Housing001.geometry} material={materials.Chrome} position={[0.552, 0.344, 0.54]} />
        <mesh geometry={nodes.Wlew_czapka001.geometry} material={materials.Chrome_Fuel_Cap} position={[0.663, 0.625, 0.113]} />
        <mesh geometry={nodes.Wlew_dol001.geometry} material={materials.Chrome_Fuel_Cap} position={[0.599, 0.625, 0.113]} />
        <mesh geometry={nodes.Wlew_jezyk001.geometry} material={materials.Chrome_Fuel_Cap} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_sprezynka001.geometry} material={materials.Metal} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_zawias_A001.geometry} material={materials.Metal_Rough} position={[0.536, 0.61, 0.111]} />
        <mesh geometry={nodes.Wlew_zawias_B001.geometry} material={materials.Chrome_dark} position={[0.663, 0.625, 0.113]} />
        <mesh geometry={nodes.Zderzak_lezka003.geometry} material={materials.Chrome} position={[0.425, 0.283, 0.544]} />
        <mesh geometry={nodes.Zderzak_lezka001001.geometry} material={materials.Chrome} position={[-0.425, 0.283, 0.544]} />
        <mesh geometry={nodes.Zderzak_lezka_lacznik001_1.geometry} material={materials.Metal} position={[0.425, 0.222, 0.579]} />
        <mesh geometry={nodes.Zderzak_lezka_lacznik001001.geometry} material={materials.Metal} position={[-0.425, 0.222, 0.579]} />
      </group>
    </group>
  )
}

useGLTF.preload('/armchiarCobra.gltf')
