/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./sofa.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SofaCobra/sofa.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={2.228}>
        <mesh geometry={nodes.Blackbody.geometry} material={materials.Flat_Black} position={[0, 0.12, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Body.geometry} material={materials.Paint_Main} position={[0, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Body_pasy002.geometry} material={materials.Stripes} position={[0, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder001001.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder002001.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder003001.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder011001.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder012001.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder016001.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder017.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder018.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder019.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder020.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder021.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder022.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder023.geometry} material={materials.Chrome} position={[-0.302, 0.12, -0.261]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_obwodka_A.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_obwodka_B.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_cylinder.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_logo.geometry} material={materials.Chrome} position={[-0.365, 0.213, -0.251]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_logo001.geometry} material={materials.Chrome} position={[0.364, 0.213, -0.251]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_uszczelka.geometry} material={materials.Rubber} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_rusztowanie.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_rusztowanie002.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_wn.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Migacz_obudowa001.geometry} material={materials.Chrome} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Migacz_uszczelka001.geometry} material={materials.Chrome} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <group position={[0.365, 0.214, -0.252]} rotation={[Math.PI / 2, 0, 3.141]} scale={[0.001, 0.012, 0.012]}>
          <mesh geometry={nodes.Plane001_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials.Body_dark} />
        </group>
        <group position={[-0.365, 0.214, -0.252]} rotation={[Math.PI / 2, 0, 3.141]} scale={[0.001, 0.012, 0.012]}>
          <mesh geometry={nodes.Plane112.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane112_1.geometry} material={materials.Body_dark} />
        </group>
        <mesh geometry={nodes.Siatka_bok.geometry} material={materials.Chrome} position={[0, 0.079, -0.212]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_dol.geometry} material={materials.Chrome} position={[0, 0.079, -0.223]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_gora.geometry} material={materials.Chrome} position={[0, 0.132, -0.229]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_plane.geometry} material={materials.Flat_Black} position={[0, 0.079, -0.226]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko002.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko005.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko006.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko_bok001.geometry} material={materials.Leather_Sofa} position={[0, 0.131, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko_bok002.geometry} material={materials.Leather_Sofa} position={[0, 0.131, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Sphere001.geometry} material={materials['Glass white']} position={[-0.365, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Glass Sofa HEadlights']} position={[-0.365, 0.133, -0.214]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Spod.geometry} material={materials.Flat_Black} position={[0, 0.12, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Szew2019.geometry} material={materials.Stitch} position={[-0.289, 0.169, 0.011]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Szew2019001.geometry} material={materials.Stitch} position={[-0.289, 0.168, 0.011]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Zderzak_lezka001.geometry} material={materials.Chrome} position={[-0.302, 0.107, -0.245]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
      <group scale={2.228}>
        <mesh geometry={nodes.Lampa_klosz.geometry} material={materials['Glass Sofa HEadlights.005']} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
      <group scale={2.228}>
        <mesh geometry={nodes.Migacz_klosz.geometry} material={materials['Glass Orange.001']} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
      <group scale={2.228}>
        <mesh geometry={nodes.Blackbody001.geometry} material={materials.Flat_Black} position={[0, 0.12, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Body001.geometry} material={materials.Paint_Main} position={[0, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Body_pasy003.geometry} material={materials.Stripes} position={[0, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder001002.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder002002.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder003002.geometry} material={materials.Chrome_dark} position={[-0.353, 0, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder011002.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder012002.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder016002.geometry} material={materials.Chrome_dark} position={[-0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder017001.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder018001.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder019001.geometry} material={materials.Chrome_dark} position={[0.353, 0, -0.142]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder020001.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder021001.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder022001.geometry} material={materials.Chrome_dark} position={[0.288, 0, 0.137]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Cylinder023001.geometry} material={materials.Chrome} position={[-0.302, 0.12, -0.261]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_obwodka_A001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_obwodka_B001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_cylinder001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_logo002.geometry} material={materials.Chrome} position={[-0.365, 0.213, -0.251]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_logo003.geometry} material={materials.Chrome} position={[0.364, 0.213, -0.251]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_p_uszczelka001.geometry} material={materials.Rubber} position={[-0.365, 0.214, -0.234]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_rusztowanie001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_rusztowanie002001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_wn001.geometry} material={materials.Chrome} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Migacz_obudowa002.geometry} material={materials.Chrome} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Migacz_uszczelka002.geometry} material={materials.Chrome} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <group position={[-0.365, 0.214, -0.252]} rotation={[Math.PI / 2, 0, 3.141]} scale={[0.001, 0.012, 0.012]}>
          <mesh geometry={nodes.Plane002_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane002_2.geometry} material={materials.Body_dark} />
        </group>
        <group position={[0.365, 0.214, -0.252]} rotation={[Math.PI / 2, 0, 3.141]} scale={[0.001, 0.012, 0.012]}>
          <mesh geometry={nodes.Plane003_1.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials.Body_dark} />
        </group>
        <mesh geometry={nodes.Siatka_bok001.geometry} material={materials.Chrome} position={[0, 0.079, -0.212]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_dol001.geometry} material={materials.Chrome} position={[0, 0.079, -0.223]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_gora001.geometry} material={materials.Chrome} position={[0, 0.132, -0.229]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siatka_plane001.geometry} material={materials.Flat_Black} position={[0, 0.079, -0.226]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko001.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko007.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko008.geometry} material={materials.Leather_Sofa} position={[0, 0.132, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko_bok003.geometry} material={materials.Leather_Sofa} position={[0, 0.131, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Siedzisko_bok004.geometry} material={materials.Leather_Sofa} position={[0, 0.131, -0.016]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Sphere001001.geometry} material={materials['Glass white']} position={[-0.365, 0.214, -0.235]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Spod001.geometry} material={materials.Flat_Black} position={[0, 0.12, -0.141]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Szew2019002.geometry} material={materials.Stitch} position={[-0.289, 0.169, 0.011]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Szew2019003.geometry} material={materials.Stitch} position={[-0.289, 0.168, 0.011]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Zderzak_lezka002.geometry} material={materials.Chrome} position={[-0.302, 0.107, -0.245]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
      <group scale={2.228}>
        <mesh geometry={nodes.Lampa_klosz001.geometry} material={materials['Glass Sofa HEadlights.001']} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
        <mesh geometry={nodes.Lampa_klosz002.geometry} material={materials['Glass Sofa HEadlights.006']} position={[-0.365, 0.214, -0.242]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
      <group scale={2.228}>
        <mesh geometry={nodes.Migacz_klosz001.geometry} material={materials['Glass Orange.003']} position={[-0.365, 0.133, -0.213]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.449} />
      </group>
    </group>
  )
}

useGLTF.preload('/sofa.gltf')
